/* ------------------------------------------------------------------
   CONTENU PAR DÉFAUT — filet de sécurité
   Utilisé uniquement si la base de données D1 est indisponible
   (ex : `next dev` local sans wrangler). En production, tout le
   contenu vient de la base D1 et se gère depuis /admin.
------------------------------------------------------------------- */

export const DEFAULTS = {
  settings: {
    site_name: "IMPACT TECH",
    phone_display: "+237 6 00 00 00 00",
    phone_link: "+237600000000",
    email: "contact@impacttech.cm",
    address: "Douala, Cameroun 🇨🇲",
    hours: "Lundi – Samedi : 8h – 18h",
    location_note: "Rendez-vous en présentiel à Douala ou en visio partout ailleurs.",
    hours_note: "Urgence sur un site en production ? WhatsApp, 7j/7.",
    facebook: "https://www.facebook.com/impacttech",
    linkedin: "https://www.linkedin.com/company/impacttech",
    instagram: "https://www.instagram.com/impacttech",
    marquee_items: ["Landing Page", "E-commerce", "SaaS", "Application", "Blog"],
    hero_pills: ["Sans engagement", "Livraison rapide", "Support local"],
  },

  stats: [
    { value: 60, suffix: "+", label: "Projets livrés", note: "sites, apps et plateformes" },
    { value: 40, suffix: "+", label: "Clients accompagnés", note: "au Cameroun et ailleurs" },
    { value: 14, suffix: " jours", label: "Délai moyen", note: "pour une landing page" },
    { value: 98, suffix: "%", label: "Recommandation", note: "de clients satisfaits" },
  ],

  services: [
    {
      slug: "landing-page",
      tag: "Conversion",
      title: "Landing Page",
      shortDesc: "Une page qui convertit vos visiteurs en clients.",
      headline: "Une page qui convertit vos visiteurs en clients",
      accent: "convertit",
      description:
        "Une page unique, rapide et percutante, construite autour d'un seul objectif : transformer vos visiteurs en contacts ou en ventes. Idéale pour lancer un produit, une campagne publicitaire ou valider une idée.",
      features: [
        "Design sur-mesure aligné à votre marque",
        "Textes optimisés pour la conversion",
        "Formulaire de contact / WhatsApp intégré",
        "Nom de domaine + hébergement 1 an",
        "Certificat SSL (https) + optimisation vitesse",
        "Référencement Google de base (SEO)",
      ],
      ideal: "Lancements produit · Campagnes pub · Événements · Indépendants",
      price: "200 000 FCFA",
      delay: "≈ 2 semaines",
      image: "/images/service-landing.jpg",
    },
    {
      slug: "e-commerce",
      tag: "Vente en ligne",
      title: "Site E-commerce",
      shortDesc: "Vendez en ligne, simplement et en toute sécurité.",
      headline: "Vendez en ligne, simplement et en toute sécurité",
      accent: "vendez",
      description:
        "Une boutique complète pour vendre 24h/24 : catalogue produits, panier, paiement Mobile Money et cartes bancaires, gestion des commandes. On vous forme pour être 100% autonome.",
      features: [
        "Catalogue produits illimité + recherche",
        "Paiement MTN MoMo, Orange Money & cartes",
        "Gestion des commandes et des stocks",
        "Design, dev, domaine & hébergement 1 an",
        "Sécurité SSL + protection des données clients",
        "Formation à la gestion + support 3 mois",
      ],
      ideal: "Boutiques · Marques · Grossistes · Restaurants (commande en ligne)",
      price: "500 000 FCFA",
      delay: "≈ 4-6 semaines",
      image: "/images/service-ecommerce.jpg",
    },
    {
      slug: "blog-vitrine",
      tag: "Visibilité",
      title: "Blog / Vitrine",
      shortDesc: "Racontez votre histoire, gagnez en visibilité.",
      headline: "Racontez votre histoire, gagnez en visibilité",
      accent: "histoire",
      description:
        "Un site élégant qui présente votre activité, vos valeurs et vos réalisations. Avec un espace blog pour publier vos actualités et améliorer votre position sur Google mois après mois.",
      features: [
        "Pages : accueil, à propos, services, contact",
        "Espace blog administrable sans coder",
        "Galerie photos / portfolio",
        "Domaine + hébergement 1 an + SSL",
        "SEO de base + Google Business Profile",
        "Formation à la publication d'articles",
      ],
      ideal: "PME · Cabinets · Artisans · ONG · Professions libérales",
      price: "300 000 FCFA",
      delay: "≈ 3 semaines",
      image: "/images/service-blog.jpg",
    },
    {
      slug: "saas",
      tag: "Produit",
      title: "SaaS",
      shortDesc: "Votre logiciel en ligne, conçu pour grandir avec vous.",
      headline: "Votre logiciel en ligne, conçu pour grandir avec vous",
      accent: "grandir",
      description:
        "De l'idée au produit : on conçoit et développe votre logiciel en ligne (abonnements, tableaux de bord, multi-utilisateurs). Architecture solide, pensée pour évoluer sans tout reconstruire.",
      features: [
        "Cadrage produit & maquettes interactives",
        "Développement MVP en cycles courts",
        "Comptes utilisateurs, rôles & abonnements",
        "Tableau de bord & statistiques",
        "Infrastructure cloud sécurisée & sauvegardes",
        "Maintenance évolutive & accompagnement",
      ],
      ideal: "Startups · Éditeurs · Entreprises qui automatisent un métier",
      price: "Sur devis",
      delay: "MVP ≈ 6-10 semaines",
      image: "/images/service-saas.jpg",
    },
    {
      slug: "application",
      tag: "Web & mobile",
      title: "Application",
      shortDesc: "Web ou mobile, pensée pour vos utilisateurs.",
      headline: "Web ou mobile, pensée pour vos utilisateurs",
      accent: "utilisateurs",
      description:
        "Application web ou mobile (Android / iOS) avec une vraie démarche UX : simple à prendre en main, rapide même en connexion faible, et adaptée aux usages locaux.",
      features: [
        "Ateliers UX & prototypes cliquables",
        "App web (PWA) ou mobile native/hybride",
        "Mode hors-ligne & performance 3G",
        "Notifications push & Mobile Money si besoin",
        "Publication Play Store / App Store",
        "Suivi, correctifs & évolutions",
      ],
      ideal: "Services de livraison · Fintech · Éducation · Communautés",
      price: "Sur devis",
      delay: "≈ 8-12 semaines",
      image: "/images/service-app.jpg",
    },
    {
      slug: "sur-mesure",
      tag: "Entreprises",
      title: "Sur-mesure",
      shortDesc: "Une solution digitale taillée pour votre entreprise.",
      headline: "Une solution digitale taillée pour votre entreprise",
      accent: "taillée",
      description:
        "Outil de gestion interne, plateforme métier, intranet, automatisation... On analyse vos processus et on construit exactement l'outil qu'il vous faut — pas un logiciel générique de plus.",
      features: [
        "Audit gratuit de vos processus",
        "Cahier des charges co-construit",
        "Intégration à vos outils existants",
        "Formation complète de vos équipes",
        "Hébergement sécurisé ou sur vos serveurs",
        "Contrat de maintenance dédié",
      ],
      ideal: "PME & grandes entreprises · Administrations · Écoles · Cliniques",
      price: "Sur devis",
      delay: "Selon projet",
      image: "/images/service-custom.jpg",
    },
  ],

  offers: [
    {
      tag: "Pack Landing Page",
      title: "Votre page qui convertit, clé en main",
      price: "200 000",
      isQuote: false,
      popular: false,
      features: [
        "Design sur-mesure + développement",
        "Nom de domaine + hébergement 1 an",
        "Sécurité SSL (https) incluse",
        "Optimisation mobile & référencement",
      ],
      image: "/images/project-landing.jpg",
    },
    {
      tag: "Pack E-commerce",
      title: "Votre boutique en ligne complète",
      price: "500 000",
      isQuote: false,
      popular: true,
      features: [
        "Boutique complète + paiement Mobile Money",
        "Design, dev, domaine & hébergement 1 an",
        "Sécurité SSL + protection des données",
        "Formation à la gestion + support 3 mois",
      ],
      image: "/images/project-ecommerce.jpg",
    },
    {
      tag: "Pack Sur-mesure",
      title: "La solution taillée pour votre entreprise",
      price: "Sur devis",
      isQuote: true,
      popular: false,
      features: [
        "Analyse de vos besoins offerte",
        "App, SaaS ou plateforme métier",
        "Infrastructure sécurisée & évolutive",
        "Accompagnement & maintenance dédiés",
      ],
      image: "/images/project-custom.jpg",
    },
  ],

  testimonials: [
    { name: "Aïcha N.", role: "Fondatrice, boutique de mode — Douala", text: "Ma boutique en ligne a été livrée en 3 semaines, paiement Mobile Money inclus. Mes ventes ont doublé dès le deuxième mois.", initials: "AN" },
    { name: "Serge M.", role: "Gérant de restaurant — Bonapriso", text: "Enfin une agence qui parle simplement ! Prix annoncé = prix payé. Ma page reçoit des réservations tous les jours.", initials: "SM" },
    { name: "Clarisse T.", role: "Consultante indépendante — Yaoundé", text: "Site vitrine élégant, livré rapidement, et l'équipe reste disponible sur WhatsApp quand j'ai une question. Je recommande.", initials: "CT" },
    { name: "Jean-Paul K.", role: "Directeur, PME logistique — Douala", text: "Notre outil de suivi sur-mesure a remplacé trois fichiers Excel. L'équipe a vraiment compris notre métier avant de coder.", initials: "JK" },
    { name: "Mireille B.", role: "Coach & formatrice — Bafoussam", text: "J'avais un petit budget, ils ont trouvé une formule adaptée sans sacrifier la qualité. Le digital accessible, c'est vrai.", initials: "MB" },
    { name: "Éric F.", role: "Startup fintech — Douala", text: "Le MVP de notre SaaS est sorti en 6 semaines. Code propre, bonne archi, on a levé nos premiers fonds avec cette démo.", initials: "EF" },
    { name: "Nadège E.", role: "ONG locale — Limbé", text: "Site multilingue, don en ligne, formation de notre équipe : tout était compris. Un vrai partenaire, pas juste un prestataire.", initials: "NE" },
    { name: "Boris A.", role: "Agence immobilière — Bonamoussadi", text: "Nos annonces sont en ligne en deux clics et les clients nous trouvent sur Google. Meilleur investissement de l'année.", initials: "BA" },
    { name: "Sandrine P.", role: "Pâtisserie artisanale — Akwa", text: "Ils ont créé une identité qui me ressemble et un site aussi gourmand que mes gâteaux. Les commandes arrivent via le site !", initials: "SP" },
  ],

  faqs: [
    { q: "Le prix affiché est-il vraiment tout compris ?", a: "Oui. Design, développement, nom de domaine, hébergement la première année, certificat SSL et mise en ligne sont inclus. La seule dépense future est le renouvellement domaine + hébergement (à partir de la 2e année), annoncé dès le devis." },
    { q: "Puis-je payer en plusieurs fois ?", a: "Oui. En général : un acompte au démarrage, un paiement à la validation du design, et le solde à la livraison. On s'adapte à votre trésorerie — parlons-en simplement." },
    { q: "Combien de temps pour avoir mon site en ligne ?", a: "Une landing page est livrée en 2 semaines environ, un site vitrine en 3 semaines, un e-commerce en 4 à 6 semaines. Le délai exact est fixé dans le devis et on s'y tient." },
    { q: "Pourrai-je modifier mon site moi-même ?", a: "Oui. On vous livre un espace d'administration simple et on vous forme (en visio ou à Douala). Textes, photos, articles, produits : vous êtes autonome. Et si besoin, notre support reste disponible." },
    { q: "Proposez-vous le paiement Mobile Money sur les boutiques ?", a: "Absolument — c'est même indispensable au Cameroun. On intègre MTN Mobile Money, Orange Money et les cartes bancaires selon vos besoins." },
    { q: "Que se passe-t-il après la livraison ?", a: "Chaque pack inclut une période de support (corrections, questions, petites retouches). Ensuite, vous pouvez continuer en toute autonomie ou souscrire une maintenance mensuelle légère." },
  ],

  posts: [
    { title: "Mobile Money sur votre site : pourquoi c'est indispensable au Cameroun", category: "Conseils", date: "28 juin 2026", readTime: "5 min", excerpt: "MTN MoMo et Orange Money représentent l'écrasante majorité des paiements en ligne au Cameroun. Si votre boutique n'accepte que la carte bancaire, vous perdez des ventes chaque jour. Voici comment intégrer le paiement mobile, combien ça coûte et les pièges à éviter.", image: "/images/blog-1.jpg", featured: true },
    { title: "Combien coûte vraiment un site web professionnel en 2026 ?", category: "Guide", date: "15 juin 2026", readTime: "7 min", excerpt: "Domaine, hébergement, design, maintenance : on décompose tout, sans langue de bois.", image: "/images/blog-2.jpg", featured: false },
    { title: "De la boutique de quartier à 100 commandes en ligne par mois", category: "Success story", date: "2 juin 2026", readTime: "4 min", excerpt: "Comment un commerçant de Douala a digitalisé son activité avec un simple pack e-commerce.", image: "/images/blog-3.jpg", featured: false },
    { title: "5 signes que votre entreprise a besoin d'un site web (maintenant)", category: "Conseils", date: "20 mai 2026", readTime: "6 min", excerpt: "Vos clients vous cherchent sur Google et trouvent... vos concurrents. On fait le point.", image: "/images/service-blog.jpg", featured: false },
    { title: "SaaS, application, site web : quelle solution pour votre idée ?", category: "Guide", date: "8 mai 2026", readTime: "8 min", excerpt: "Les différences expliquées simplement, avec des exemples et des budgets réalistes.", image: "/images/service-saas.jpg", featured: false },
    { title: "Tok Tok Livraison : une app pensée pour les rues de Douala", category: "Success story", date: "25 avril 2026", readTime: "5 min", excerpt: "Suivi en temps réel, paiement mobile, mode hors-ligne : les coulisses d'une app locale.", image: "/images/project-delivery.jpg", featured: false },
    { title: "Landing page : 7 éléments qui font (vraiment) convertir", category: "Conseils", date: "10 avril 2026", readTime: "4 min", excerpt: "Titre, preuve sociale, appel à l'action... la checklist qu'on applique sur chaque projet.", image: "/images/service-landing.jpg", featured: false },
  ],

  projects: [
    { title: "Saveurs du Wouri — restaurant", category: "Landing Page", description: "Landing de réservation avec menu du jour et WhatsApp direct.", result: "+40 réservations / mois", image: "/images/project-landing.jpg" },
    { title: "Kmer Style — mode & wax", category: "E-commerce", description: "Boutique en ligne avec paiement MTN MoMo et Orange Money.", result: "Ventes x2 en 2 mois", image: "/images/project-ecommerce.jpg" },
    { title: "Cabinet Nkotti — conseil juridique", category: "Vitrine", description: "Site vitrine sobre et crédible, avec blog d'actualités juridiques.", result: "1er sur Google local", image: "/images/service-blog.jpg" },
    { title: "GestiStock — SaaS de gestion", category: "SaaS & App", description: "MVP SaaS de gestion de stock pour commerces, multi-boutiques.", result: "MVP livré en 8 semaines", image: "/images/service-saas.jpg" },
    { title: "Tok Tok Livraison — app mobile", category: "SaaS & App", description: "Application de livraison avec suivi en temps réel et paiement mobile.", result: "5 000+ livraisons suivies", image: "/images/project-delivery.jpg" },
    { title: "Collège Les Bâtisseurs — plateforme", category: "Sur-mesure", description: "Portail notes & scolarité : parents, élèves et administration connectés.", result: "800 familles utilisatrices", image: "/images/project-school.jpg" },
    { title: "Immo Littoral — programme neuf", category: "Landing Page", description: "Page de captation de prospects pour un programme immobilier.", result: "120 prospects qualifiés", image: "/images/service-landing.jpg" },
    { title: "TransCam Logistics — outil interne", category: "Sur-mesure", description: "Suivi de flotte et des expéditions, tableaux de bord dirigeants.", result: "-30% de temps administratif", image: "/images/project-custom.jpg" },
    { title: "Artisanat Bafoussam — export", category: "E-commerce", description: "Boutique bilingue FR/EN pour vendre l'artisanat camerounais à l'international.", result: "Clients dans 12 pays", image: "/images/blog-3.jpg" },
  ],

  processSteps: [
    { num: "01", title: "Échange", description: "On écoute votre projet, vos objectifs et votre budget. Premier rendez-vous gratuit, en ligne ou à Douala." },
    { num: "02", title: "Devis clair", description: "Sous 48h, vous recevez une proposition détaillée : prix fixe, délais, livrables. Zéro frais caché." },
    { num: "03", title: "Design & Dev", description: "On conçoit, vous validez à chaque étape. Vous suivez l'avancement en temps réel, sans jargon technique." },
    { num: "04", title: "Livraison & suivi", description: "Mise en ligne, formation à la prise en main et support continu. On reste à vos côtés après la livraison." },
  ],
};
