-- Généré par scripts/gen-seed.mjs — ne pas éditer à la main.

DELETE FROM services;
INSERT INTO services (slug, tag, title, short_desc, headline, accent, description, features, ideal, price, delay, image, sort_order, active) VALUES
('landing-page', 'Conversion', 'Landing Page', 'Une page qui convertit vos visiteurs en clients.', 'Une page qui convertit vos visiteurs en clients', 'convertit', 'Une page unique, rapide et percutante, construite autour d''un seul objectif : transformer vos visiteurs en contacts ou en ventes. Idéale pour lancer un produit, une campagne publicitaire ou valider une idée.', '["Design sur-mesure aligné à votre marque","Textes optimisés pour la conversion","Formulaire de contact / WhatsApp intégré","Nom de domaine + hébergement 1 an","Certificat SSL (https) + optimisation vitesse","Référencement Google de base (SEO)"]', 'Lancements produit · Campagnes pub · Événements · Indépendants', '200 000 FCFA', '≈ 2 semaines', '/images/service-landing.jpg', 0, 1),
('e-commerce', 'Vente en ligne', 'Site E-commerce', 'Vendez en ligne, simplement et en toute sécurité.', 'Vendez en ligne, simplement et en toute sécurité', 'vendez', 'Une boutique complète pour vendre 24h/24 : catalogue produits, panier, paiement Mobile Money et cartes bancaires, gestion des commandes. On vous forme pour être 100% autonome.', '["Catalogue produits illimité + recherche","Paiement MTN MoMo, Orange Money & cartes","Gestion des commandes et des stocks","Design, dev, domaine & hébergement 1 an","Sécurité SSL + protection des données clients","Formation à la gestion + support 3 mois"]', 'Boutiques · Marques · Grossistes · Restaurants (commande en ligne)', '500 000 FCFA', '≈ 4-6 semaines', '/images/service-ecommerce.jpg', 1, 1),
('blog-vitrine', 'Visibilité', 'Blog / Vitrine', 'Racontez votre histoire, gagnez en visibilité.', 'Racontez votre histoire, gagnez en visibilité', 'histoire', 'Un site élégant qui présente votre activité, vos valeurs et vos réalisations. Avec un espace blog pour publier vos actualités et améliorer votre position sur Google mois après mois.', '["Pages : accueil, à propos, services, contact","Espace blog administrable sans coder","Galerie photos / portfolio","Domaine + hébergement 1 an + SSL","SEO de base + Google Business Profile","Formation à la publication d''articles"]', 'PME · Cabinets · Artisans · ONG · Professions libérales', '300 000 FCFA', '≈ 3 semaines', '/images/service-blog.jpg', 2, 1),
('saas', 'Produit', 'SaaS', 'Votre logiciel en ligne, conçu pour grandir avec vous.', 'Votre logiciel en ligne, conçu pour grandir avec vous', 'grandir', 'De l''idée au produit : on conçoit et développe votre logiciel en ligne (abonnements, tableaux de bord, multi-utilisateurs). Architecture solide, pensée pour évoluer sans tout reconstruire.', '["Cadrage produit & maquettes interactives","Développement MVP en cycles courts","Comptes utilisateurs, rôles & abonnements","Tableau de bord & statistiques","Infrastructure cloud sécurisée & sauvegardes","Maintenance évolutive & accompagnement"]', 'Startups · Éditeurs · Entreprises qui automatisent un métier', 'Sur devis', 'MVP ≈ 6-10 semaines', '/images/service-saas.jpg', 3, 1),
('application', 'Web & mobile', 'Application', 'Web ou mobile, pensée pour vos utilisateurs.', 'Web ou mobile, pensée pour vos utilisateurs', 'utilisateurs', 'Application web ou mobile (Android / iOS) avec une vraie démarche UX : simple à prendre en main, rapide même en connexion faible, et adaptée aux usages locaux.', '["Ateliers UX & prototypes cliquables","App web (PWA) ou mobile native/hybride","Mode hors-ligne & performance 3G","Notifications push & Mobile Money si besoin","Publication Play Store / App Store","Suivi, correctifs & évolutions"]', 'Services de livraison · Fintech · Éducation · Communautés', 'Sur devis', '≈ 8-12 semaines', '/images/service-app.jpg', 4, 1),
('sur-mesure', 'Entreprises', 'Sur-mesure', 'Une solution digitale taillée pour votre entreprise.', 'Une solution digitale taillée pour votre entreprise', 'taillée', 'Outil de gestion interne, plateforme métier, intranet, automatisation... On analyse vos processus et on construit exactement l''outil qu''il vous faut — pas un logiciel générique de plus.', '["Audit gratuit de vos processus","Cahier des charges co-construit","Intégration à vos outils existants","Formation complète de vos équipes","Hébergement sécurisé ou sur vos serveurs","Contrat de maintenance dédié"]', 'PME & grandes entreprises · Administrations · Écoles · Cliniques', 'Sur devis', 'Selon projet', '/images/service-custom.jpg', 5, 1);

DELETE FROM projects;
INSERT INTO projects (title, category, description, result, image, sort_order, active) VALUES
('Saveurs du Wouri — restaurant', 'Landing Page', 'Landing de réservation avec menu du jour et WhatsApp direct.', '+40 réservations / mois', '/images/project-landing.jpg', 0, 1),
('Kmer Style — mode & wax', 'E-commerce', 'Boutique en ligne avec paiement MTN MoMo et Orange Money.', 'Ventes x2 en 2 mois', '/images/project-ecommerce.jpg', 1, 1),
('Cabinet Nkotti — conseil juridique', 'Vitrine', 'Site vitrine sobre et crédible, avec blog d''actualités juridiques.', '1er sur Google local', '/images/service-blog.jpg', 2, 1),
('GestiStock — SaaS de gestion', 'SaaS & App', 'MVP SaaS de gestion de stock pour commerces, multi-boutiques.', 'MVP livré en 8 semaines', '/images/service-saas.jpg', 3, 1),
('Tok Tok Livraison — app mobile', 'SaaS & App', 'Application de livraison avec suivi en temps réel et paiement mobile.', '5 000+ livraisons suivies', '/images/project-delivery.jpg', 4, 1),
('Collège Les Bâtisseurs — plateforme', 'Sur-mesure', 'Portail notes & scolarité : parents, élèves et administration connectés.', '800 familles utilisatrices', '/images/project-school.jpg', 5, 1),
('Immo Littoral — programme neuf', 'Landing Page', 'Page de captation de prospects pour un programme immobilier.', '120 prospects qualifiés', '/images/service-landing.jpg', 6, 1),
('TransCam Logistics — outil interne', 'Sur-mesure', 'Suivi de flotte et des expéditions, tableaux de bord dirigeants.', '-30% de temps administratif', '/images/project-custom.jpg', 7, 1),
('Artisanat Bafoussam — export', 'E-commerce', 'Boutique bilingue FR/EN pour vendre l''artisanat camerounais à l''international.', 'Clients dans 12 pays', '/images/blog-3.jpg', 8, 1);

DELETE FROM testimonials;
INSERT INTO testimonials (name, role, text, initials, sort_order, active) VALUES
('Aïcha N.', 'Fondatrice, boutique de mode — Douala', 'Ma boutique en ligne a été livrée en 3 semaines, paiement Mobile Money inclus. Mes ventes ont doublé dès le deuxième mois.', 'AN', 0, 1),
('Serge M.', 'Gérant de restaurant — Bonapriso', 'Enfin une agence qui parle simplement ! Prix annoncé = prix payé. Ma page reçoit des réservations tous les jours.', 'SM', 1, 1),
('Clarisse T.', 'Consultante indépendante — Yaoundé', 'Site vitrine élégant, livré rapidement, et l''équipe reste disponible sur WhatsApp quand j''ai une question. Je recommande.', 'CT', 2, 1),
('Jean-Paul K.', 'Directeur, PME logistique — Douala', 'Notre outil de suivi sur-mesure a remplacé trois fichiers Excel. L''équipe a vraiment compris notre métier avant de coder.', 'JK', 3, 1),
('Mireille B.', 'Coach & formatrice — Bafoussam', 'J''avais un petit budget, ils ont trouvé une formule adaptée sans sacrifier la qualité. Le digital accessible, c''est vrai.', 'MB', 4, 1),
('Éric F.', 'Startup fintech — Douala', 'Le MVP de notre SaaS est sorti en 6 semaines. Code propre, bonne archi, on a levé nos premiers fonds avec cette démo.', 'EF', 5, 1),
('Nadège E.', 'ONG locale — Limbé', 'Site multilingue, don en ligne, formation de notre équipe : tout était compris. Un vrai partenaire, pas juste un prestataire.', 'NE', 6, 1),
('Boris A.', 'Agence immobilière — Bonamoussadi', 'Nos annonces sont en ligne en deux clics et les clients nous trouvent sur Google. Meilleur investissement de l''année.', 'BA', 7, 1),
('Sandrine P.', 'Pâtisserie artisanale — Akwa', 'Ils ont créé une identité qui me ressemble et un site aussi gourmand que mes gâteaux. Les commandes arrivent via le site !', 'SP', 8, 1);

DELETE FROM stats;
INSERT INTO stats (value, suffix, label, note, sort_order, active) VALUES
(60, '+', 'Projets livrés', 'sites, apps et plateformes', 0, 1),
(40, '+', 'Clients accompagnés', 'au Cameroun et ailleurs', 1, 1),
(14, ' jours', 'Délai moyen', 'pour une landing page', 2, 1),
(98, '%', 'Recommandation', 'de clients satisfaits', 3, 1);

DELETE FROM faqs;
INSERT INTO faqs (question, answer, sort_order, active) VALUES
('Le prix affiché est-il vraiment tout compris ?', 'Oui. Design, développement, nom de domaine, hébergement la première année, certificat SSL et mise en ligne sont inclus. La seule dépense future est le renouvellement domaine + hébergement (à partir de la 2e année), annoncé dès le devis.', 0, 1),
('Puis-je payer en plusieurs fois ?', 'Oui. En général : un acompte au démarrage, un paiement à la validation du design, et le solde à la livraison. On s''adapte à votre trésorerie — parlons-en simplement.', 1, 1),
('Combien de temps pour avoir mon site en ligne ?', 'Une landing page est livrée en 2 semaines environ, un site vitrine en 3 semaines, un e-commerce en 4 à 6 semaines. Le délai exact est fixé dans le devis et on s''y tient.', 2, 1),
('Pourrai-je modifier mon site moi-même ?', 'Oui. On vous livre un espace d''administration simple et on vous forme (en visio ou à Douala). Textes, photos, articles, produits : vous êtes autonome. Et si besoin, notre support reste disponible.', 3, 1),
('Proposez-vous le paiement Mobile Money sur les boutiques ?', 'Absolument — c''est même indispensable au Cameroun. On intègre MTN Mobile Money, Orange Money et les cartes bancaires selon vos besoins.', 4, 1),
('Que se passe-t-il après la livraison ?', 'Chaque pack inclut une période de support (corrections, questions, petites retouches). Ensuite, vous pouvez continuer en toute autonomie ou souscrire une maintenance mensuelle légère.', 5, 1);

DELETE FROM process_steps;
INSERT INTO process_steps (num, title, description, sort_order, active) VALUES
('01', 'Échange', 'On écoute votre projet, vos objectifs et votre budget. Premier rendez-vous gratuit, en ligne ou à Douala.', 0, 1),
('02', 'Devis clair', 'Sous 48h, vous recevez une proposition détaillée : prix fixe, délais, livrables. Zéro frais caché.', 1, 1),
('03', 'Design & Dev', 'On conçoit, vous validez à chaque étape. Vous suivez l''avancement en temps réel, sans jargon technique.', 2, 1),
('04', 'Livraison & suivi', 'Mise en ligne, formation à la prise en main et support continu. On reste à vos côtés après la livraison.', 3, 1);

DELETE FROM posts;
INSERT INTO posts (title, category, date, read_time, excerpt, image, featured, sort_order, active, eyebrow, lead, secondary_image, author, sections) VALUES
('Mobile Money sur votre site : pourquoi c''est indispensable au Cameroun', 'Conseils', '28 juin 2026', '5 min', 'MTN MoMo et Orange Money représentent l''écrasante majorité des paiements en ligne au Cameroun. Si votre boutique n''accepte que la carte bancaire, vous perdez des ventes chaque jour. Voici comment intégrer le paiement mobile, combien ça coûte et les pièges à éviter.', '/images/blog-1.jpg', 1, 0, 1, 'Paiement local, conversion réelle', 'Au Cameroun, proposer Mobile Money n’est pas un bonus. C’est souvent la différence entre un panier abandonné et une vente finalisée.', '/images/project-ecommerce.jpg', 'L’équipe IMPACT TECH', '[{"title":"Vos clients ont déjà leur moyen de paiement en poche","paragraphs":["Une grande partie des acheteurs locaux utilise quotidiennement MTN MoMo ou Orange Money. Leur demander une carte bancaire introduit une friction inutile au moment le plus sensible du parcours : le paiement.","Le bon réflexe consiste à afficher les options locales dès la fiche produit, puis à rendre le règlement aussi court que possible sur mobile."],"bullets":["Un numéro de téléphone suffit","Validation immédiate depuis le mobile","Parcours familier et rassurant"]},{"title":"L’intégration doit rester simple et sécurisée","paragraphs":["Une intégration professionnelle connecte votre boutique à un prestataire de paiement fiable, confirme automatiquement la transaction et associe chaque règlement à la bonne commande.","Évitez les validations manuelles par capture d’écran : elles ralentissent le traitement et augmentent les risques d’erreur."],"quote":"Le meilleur paiement est celui que le client comprend sans avoir besoin de poser une question."},{"title":"Mesurez ce qui se passe après le clic","paragraphs":["Suivez le taux de paiement réussi, les abandons et les moyens de paiement préférés. Ces données permettent d’améliorer le tunnel sans refaire toute la boutique.","Commencez avec un parcours clair, testez-le sur plusieurs téléphones et prévoyez toujours un message précis lorsque la transaction échoue."],"callout":"À retenir : Mobile Money doit être visible, rapide et confirmé automatiquement."}]'),
('Combien coûte vraiment un site web professionnel en 2026 ?', 'Guide', '15 juin 2026', '7 min', 'Domaine, hébergement, design, maintenance : on décompose tout, sans langue de bois.', '/images/blog-2.jpg', 0, 1, 1, 'Budget clair, décisions sereines', 'Le prix d’un site ne correspond pas seulement au nombre de pages. Il reflète surtout le niveau de stratégie, de design, de technologie et d’accompagnement nécessaire.', '/images/project-custom.jpg', 'L’équipe IMPACT TECH', '[{"title":"Ce que vous payez réellement","paragraphs":["Un projet sérieux commence par la compréhension de vos objectifs. Viennent ensuite l’architecture des contenus, le design, le développement, les tests et la mise en ligne.","Un devis très bas oublie souvent l’hébergement, la sécurité, le référencement ou l’accompagnement après livraison."],"bullets":["Cadrage et stratégie","Design responsive","Développement et tests","Domaine, hébergement et sécurité"]},{"title":"Choisir le bon niveau d’investissement","paragraphs":["Une landing page convient à une offre unique. Un site vitrine structure une marque. Une boutique en ligne ajoute catalogue, paiement et gestion des commandes.","Le budget doit suivre l’objectif économique du projet, pas une liste de fonctionnalités copiée chez un concurrent."],"quote":"Un site rentable n’est pas forcément le plus cher : c’est celui qui résout le bon problème."},{"title":"Les coûts à anticiper après la livraison","paragraphs":["Prévoyez le renouvellement du domaine, de l’hébergement et éventuellement un forfait de maintenance. Ces dépenses doivent être annoncées avant le lancement.","Demandez toujours ce qui est inclus, ce qui vous appartient et comment vous pourrez modifier le contenu."],"callout":"Un devis lisible doit séparer création, fonctionnement annuel et évolutions futures."}]'),
('De la boutique de quartier à 100 commandes en ligne par mois', 'Success story', '2 juin 2026', '4 min', 'Comment un commerçant de Douala a digitalisé son activité avec un simple pack e-commerce.', '/images/blog-3.jpg', 0, 2, 1, 'Success story — commerce local', 'Une petite boutique de Douala n’avait pas besoin d’une usine à gaz. Elle avait besoin d’un parcours simple pour montrer ses produits et recevoir des commandes fiables.', '/images/blog-3.jpg', 'L’équipe IMPACT TECH', '[{"title":"Partir des habitudes réelles des clients","paragraphs":["Les commandes arrivaient déjà par WhatsApp, mais les photos, prix et disponibilités étaient dispersés. La première étape a été de structurer un catalogue clair.","Nous avons conservé WhatsApp comme canal de proximité tout en ajoutant une boutique capable de centraliser les commandes."],"bullets":["Catalogue lisible sur mobile","Stocks faciles à mettre à jour","Paiement Mobile Money","Confirmation automatique"]},{"title":"Lancer petit, mesurer vite","paragraphs":["La boutique a commencé avec ses meilleures références. Les données des premières semaines ont montré les produits les plus consultés et les points de blocage.","Chaque amélioration répondait à un comportement observé : recherche plus visible, livraison mieux expliquée et relances simplifiées."],"quote":"La croissance est venue de petits ajustements réguliers, pas d’une fonctionnalité miracle."},{"title":"Transformer le site en outil quotidien","paragraphs":["Le site n’est plus une simple vitrine. Il sert à présenter, vendre, rassurer et organiser le travail de l’équipe.","Le résultat le plus important reste l’autonomie : la commerçante peut gérer ses produits sans attendre un développeur."],"callout":"100 commandes mensuelles deviennent possibles quand le parcours est simple pour le client et pour l’équipe."}]'),
('5 signes que votre entreprise a besoin d''un site web (maintenant)', 'Conseils', '20 mai 2026', '6 min', 'Vos clients vous cherchent sur Google et trouvent... vos concurrents. On fait le point.', '/images/service-blog.jpg', 0, 3, 1, 'Visibilité et crédibilité', 'Si vos clients vous cherchent en ligne et ne trouvent qu’un numéro perdu dans une publication, votre entreprise laisse déjà des opportunités à ses concurrents.', '/images/service-blog.jpg', 'L’équipe IMPACT TECH', '[{"title":"On vous pose toujours les mêmes questions","paragraphs":["Prix, horaires, localisation, services : un site répond immédiatement aux questions répétitives et permet à votre équipe de se concentrer sur les échanges importants."],"bullets":["Votre activité dépend uniquement des réseaux sociaux","Vos offres sont difficiles à comparer","Votre crédibilité doit être expliquée à chaque prospect"]},{"title":"Vos concurrents occupent Google à votre place","paragraphs":["Les réseaux sociaux créent de l’attention, mais un site construit une présence durable. Il rassemble vos contenus et donne à Google une source fiable à référencer.","Même un site court peut devenir un avantage s’il répond précisément aux recherches de vos clients."],"quote":"Ne pas être trouvé en ligne revient souvent à ne pas être considéré."},{"title":"Vous perdez du temps dans des tâches manuelles","paragraphs":["Demandes de devis, réservations et inscriptions peuvent être structurées automatiquement. Le site devient alors un outil de travail, pas une brochure."],"callout":"Commencez par le besoin le plus coûteux en temps ou en opportunités."}]'),
('SaaS, application, site web : quelle solution pour votre idée ?', 'Guide', '8 mai 2026', '8 min', 'Les différences expliquées simplement, avec des exemples et des budgets réalistes.', '/images/service-saas.jpg', 0, 4, 1, 'Choisir avant de construire', 'Site, application et SaaS répondent à des problèmes différents. Le bon choix dépend moins de la mode que de l’usage attendu.', '/images/service-saas.jpg', 'L’équipe IMPACT TECH', '[{"title":"Le site informe et convertit","paragraphs":["Un site présente une offre, rassure et transforme des visiteurs en prospects ou clients. Il reste le meilleur point de départ pour de nombreuses entreprises."],"bullets":["Landing page pour une campagne","Site vitrine pour une marque","E-commerce pour vendre directement"]},{"title":"L’application accompagne un usage fréquent","paragraphs":["Une application devient pertinente lorsque l’utilisateur revient souvent, utilise des fonctions liées au téléphone ou doit travailler hors connexion.","Un SaaS, lui, organise un métier ou un processus récurrent avec des comptes, des données et souvent un abonnement."],"quote":"Ne construisez pas une application si un site mobile bien pensé résout déjà le problème."},{"title":"Valider avant d’investir lourdement","paragraphs":["Un prototype ou un MVP permet de tester la proposition de valeur avec de vrais utilisateurs. Les retours guident ensuite les fonctionnalités prioritaires."],"callout":"La meilleure technologie est celle qui permet de vérifier rapidement votre hypothèse."}]'),
('Tok Tok Livraison : une app pensée pour les rues de Douala', 'Success story', '25 avril 2026', '5 min', 'Suivi en temps réel, paiement mobile, mode hors-ligne : les coulisses d''une app locale.', '/images/project-delivery.jpg', 0, 5, 1, 'Success story — mobilité', 'Concevoir pour Douala exige de tenir compte de la connexion, des adresses informelles et des habitudes de paiement locales.', '/images/project-delivery.jpg', 'L’équipe IMPACT TECH', '[{"title":"Le terrain avant l’interface","paragraphs":["Nous avons observé le travail des livreurs, des opérateurs et des clients avant de dessiner les écrans. Les difficultés ne venaient pas seulement de la carte, mais aussi de la transmission des repères."],"bullets":["Repères textuels et vocaux","Fonctionnement en connexion faible","Statuts simples pour chaque livraison"]},{"title":"Une expérience pensée pour l’urgence","paragraphs":["Les actions principales restent accessibles d’une main. Les informations importantes utilisent des contrastes forts et les changements de statut sont immédiatement visibles.","Le mode hors ligne conserve les actions puis les synchronise dès que le réseau revient."],"quote":"Une application locale performante commence par accepter la réalité du terrain."},{"title":"Relier clients, livreurs et opérations","paragraphs":["Le tableau de bord centralise les courses, les paiements et les incidents. Chaque équipe voit uniquement ce dont elle a besoin."],"callout":"Le design utile réduit les appels, les erreurs et le temps perdu entre deux livraisons."}]'),
('Landing page : 7 éléments qui font (vraiment) convertir', 'Conseils', '10 avril 2026', '4 min', 'Titre, preuve sociale, appel à l''action... la checklist qu''on applique sur chaque projet.', '/images/service-landing.jpg', 0, 6, 1, 'Conversion sans manipulation', 'Une landing page efficace guide le visiteur vers une seule décision. Chaque bloc doit répondre à une question précise et réduire une hésitation.', '/images/service-landing.jpg', 'L’équipe IMPACT TECH', '[{"title":"Une promesse comprise en quelques secondes","paragraphs":["Le titre doit expliquer le résultat offert, pas seulement présenter le nom du produit. Le sous-titre précise pour qui l’offre existe et comment elle fonctionne."],"bullets":["Un titre orienté résultat","Un appel à l’action visible","Une preuve sociale crédible","Un visuel qui montre le produit"]},{"title":"Répondre aux objections dans le bon ordre","paragraphs":["Prix, délai, fonctionnement et garanties doivent apparaître avant que le doute ne devienne un abandon. Une FAQ courte peut lever les dernières hésitations.","Sur mobile, les informations décisives doivent arriver rapidement et le bouton principal rester facile à trouver."],"quote":"La conversion vient de la clarté, pas de la pression."},{"title":"Mesurer puis améliorer","paragraphs":["Analysez les clics, les formulaires commencés et les abandons. Changez une variable importante à la fois afin de comprendre ce qui améliore réellement les résultats."],"callout":"Une bonne landing page n’est jamais figée : elle apprend de ses visiteurs."}]');
