-- Seed D1 — contenu par défaut (src/lib/defaults.js)

INSERT INTO settings (key, value) VALUES ('site_name', 'IMPACT TECH');
INSERT INTO settings (key, value) VALUES ('phone_display', '+237 6 00 00 00 00');
INSERT INTO settings (key, value) VALUES ('phone_link', '+237600000000');
INSERT INTO settings (key, value) VALUES ('email', 'contact@impacttech.cm');
INSERT INTO settings (key, value) VALUES ('address', 'Douala, Cameroun 🇨🇲');
INSERT INTO settings (key, value) VALUES ('hours', 'Lundi – Samedi : 8h – 18h');
INSERT INTO settings (key, value) VALUES ('location_note', 'Rendez-vous en présentiel à Douala ou en visio partout ailleurs.');
INSERT INTO settings (key, value) VALUES ('hours_note', 'Urgence sur un site en production ? WhatsApp, 7j/7.');
INSERT INTO settings (key, value) VALUES ('facebook', 'https://www.facebook.com/impacttech');
INSERT INTO settings (key, value) VALUES ('linkedin', 'https://www.linkedin.com/company/impacttech');
INSERT INTO settings (key, value) VALUES ('instagram', 'https://www.instagram.com/impacttech');
INSERT INTO settings (key, value) VALUES ('marquee_items', '["Landing Page","E-commerce","SaaS","Application","Blog"]');
INSERT INTO settings (key, value) VALUES ('hero_pills', '["Sans engagement","Livraison rapide","Support local"]');

INSERT INTO stats (value, suffix, label, note, sort_order, active) VALUES (60, '+', 'Projets livrés', 'sites, apps et plateformes', 0, 1);
INSERT INTO stats (value, suffix, label, note, sort_order, active) VALUES (40, '+', 'Clients accompagnés', 'au Cameroun et ailleurs', 1, 1);
INSERT INTO stats (value, suffix, label, note, sort_order, active) VALUES (14, ' jours', 'Délai moyen', 'pour une landing page', 2, 1);
INSERT INTO stats (value, suffix, label, note, sort_order, active) VALUES (98, '%', 'Recommandation', 'de clients satisfaits', 3, 1);

INSERT INTO services (slug, tag, title, short_desc, headline, accent, description, features, ideal, price, delay, image, sort_order, active) VALUES ('landing-page', 'Conversion', 'Landing Page', 'Une page qui convertit vos visiteurs en clients.', 'Une page qui convertit vos visiteurs en clients', 'convertit', 'Une page unique, rapide et percutante, construite autour d''un seul objectif : transformer vos visiteurs en contacts ou en ventes. Idéale pour lancer un produit, une campagne publicitaire ou valider une idée.', '["Design sur-mesure aligné à votre marque","Textes optimisés pour la conversion","Formulaire de contact / WhatsApp intégré","Nom de domaine + hébergement 1 an","Certificat SSL (https) + optimisation vitesse","Référencement Google de base (SEO)"]', 'Lancements produit · Campagnes pub · Événements · Indépendants', '200 000 FCFA', '≈ 2 semaines', '/images/service-landing.jpg', 0, 1);
INSERT INTO services (slug, tag, title, short_desc, headline, accent, description, features, ideal, price, delay, image, sort_order, active) VALUES ('e-commerce', 'Vente en ligne', 'Site E-commerce', 'Vendez en ligne, simplement et en toute sécurité.', 'Vendez en ligne, simplement et en toute sécurité', 'vendez', 'Une boutique complète pour vendre 24h/24 : catalogue produits, panier, paiement Mobile Money et cartes bancaires, gestion des commandes. On vous forme pour être 100% autonome.', '["Catalogue produits illimité + recherche","Paiement MTN MoMo, Orange Money & cartes","Gestion des commandes et des stocks","Design, dev, domaine & hébergement 1 an","Sécurité SSL + protection des données clients","Formation à la gestion + support 3 mois"]', 'Boutiques · Marques · Grossistes · Restaurants (commande en ligne)', '500 000 FCFA', '≈ 4-6 semaines', '/images/service-ecommerce.jpg', 1, 1);
INSERT INTO services (slug, tag, title, short_desc, headline, accent, description, features, ideal, price, delay, image, sort_order, active) VALUES ('blog-vitrine', 'Visibilité', 'Blog / Vitrine', 'Racontez votre histoire, gagnez en visibilité.', 'Racontez votre histoire, gagnez en visibilité', 'histoire', 'Un site élégant qui présente votre activité, vos valeurs et vos réalisations. Avec un espace blog pour publier vos actualités et améliorer votre position sur Google mois après mois.', '["Pages : accueil, à propos, services, contact","Espace blog administrable sans coder","Galerie photos / portfolio","Domaine + hébergement 1 an + SSL","SEO de base + Google Business Profile","Formation à la publication d''articles"]', 'PME · Cabinets · Artisans · ONG · Professions libérales', '300 000 FCFA', '≈ 3 semaines', '/images/service-blog.jpg', 2, 1);
INSERT INTO services (slug, tag, title, short_desc, headline, accent, description, features, ideal, price, delay, image, sort_order, active) VALUES ('saas', 'Produit', 'SaaS', 'Votre logiciel en ligne, conçu pour grandir avec vous.', 'Votre logiciel en ligne, conçu pour grandir avec vous', 'grandir', 'De l''idée au produit : on conçoit et développe votre logiciel en ligne (abonnements, tableaux de bord, multi-utilisateurs). Architecture solide, pensée pour évoluer sans tout reconstruire.', '["Cadrage produit & maquettes interactives","Développement MVP en cycles courts","Comptes utilisateurs, rôles & abonnements","Tableau de bord & statistiques","Infrastructure cloud sécurisée & sauvegardes","Maintenance évolutive & accompagnement"]', 'Startups · Éditeurs · Entreprises qui automatisent un métier', 'Sur devis', 'MVP ≈ 6-10 semaines', '/images/service-saas.jpg', 3, 1);
INSERT INTO services (slug, tag, title, short_desc, headline, accent, description, features, ideal, price, delay, image, sort_order, active) VALUES ('application', 'Web & mobile', 'Application', 'Web ou mobile, pensée pour vos utilisateurs.', 'Web ou mobile, pensée pour vos utilisateurs', 'utilisateurs', 'Application web ou mobile (Android / iOS) avec une vraie démarche UX : simple à prendre en main, rapide même en connexion faible, et adaptée aux usages locaux.', '["Ateliers UX & prototypes cliquables","App web (PWA) ou mobile native/hybride","Mode hors-ligne & performance 3G","Notifications push & Mobile Money si besoin","Publication Play Store / App Store","Suivi, correctifs & évolutions"]', 'Services de livraison · Fintech · Éducation · Communautés', 'Sur devis', '≈ 8-12 semaines', '/images/service-app.jpg', 4, 1);
INSERT INTO services (slug, tag, title, short_desc, headline, accent, description, features, ideal, price, delay, image, sort_order, active) VALUES ('sur-mesure', 'Entreprises', 'Sur-mesure', 'Une solution digitale taillée pour votre entreprise.', 'Une solution digitale taillée pour votre entreprise', 'taillée', 'Outil de gestion interne, plateforme métier, intranet, automatisation... On analyse vos processus et on construit exactement l''outil qu''il vous faut — pas un logiciel générique de plus.', '["Audit gratuit de vos processus","Cahier des charges co-construit","Intégration à vos outils existants","Formation complète de vos équipes","Hébergement sécurisé ou sur vos serveurs","Contrat de maintenance dédié"]', 'PME & grandes entreprises · Administrations · Écoles · Cliniques', 'Sur devis', 'Selon projet', '/images/service-custom.jpg', 5, 1);

INSERT INTO offers (tag, title, price, is_quote, popular, features, image, sort_order, active) VALUES ('Pack Landing Page', 'Votre page qui convertit, clé en main', '200 000', 0, 0, '["Design sur-mesure + développement","Nom de domaine + hébergement 1 an","Sécurité SSL (https) incluse","Optimisation mobile & référencement"]', '/images/project-landing.jpg', 0, 1);
INSERT INTO offers (tag, title, price, is_quote, popular, features, image, sort_order, active) VALUES ('Pack E-commerce', 'Votre boutique en ligne complète', '500 000', 0, 1, '["Boutique complète + paiement Mobile Money","Design, dev, domaine & hébergement 1 an","Sécurité SSL + protection des données","Formation à la gestion + support 3 mois"]', '/images/project-ecommerce.jpg', 1, 1);
INSERT INTO offers (tag, title, price, is_quote, popular, features, image, sort_order, active) VALUES ('Pack Sur-mesure', 'La solution taillée pour votre entreprise', 'Sur devis', 1, 0, '["Analyse de vos besoins offerte","App, SaaS ou plateforme métier","Infrastructure sécurisée & évolutive","Accompagnement & maintenance dédiés"]', '/images/project-custom.jpg', 2, 1);

INSERT INTO testimonials (name, role, text, initials, sort_order, active) VALUES ('Aïcha N.', 'Fondatrice, boutique de mode — Douala', 'Ma boutique en ligne a été livrée en 3 semaines, paiement Mobile Money inclus. Mes ventes ont doublé dès le deuxième mois.', 'AN', 0, 1);
INSERT INTO testimonials (name, role, text, initials, sort_order, active) VALUES ('Serge M.', 'Gérant de restaurant — Bonapriso', 'Enfin une agence qui parle simplement ! Prix annoncé = prix payé. Ma page reçoit des réservations tous les jours.', 'SM', 1, 1);
INSERT INTO testimonials (name, role, text, initials, sort_order, active) VALUES ('Clarisse T.', 'Consultante indépendante — Yaoundé', 'Site vitrine élégant, livré rapidement, et l''équipe reste disponible sur WhatsApp quand j''ai une question. Je recommande.', 'CT', 2, 1);
INSERT INTO testimonials (name, role, text, initials, sort_order, active) VALUES ('Jean-Paul K.', 'Directeur, PME logistique — Douala', 'Notre outil de suivi sur-mesure a remplacé trois fichiers Excel. L''équipe a vraiment compris notre métier avant de coder.', 'JK', 3, 1);
INSERT INTO testimonials (name, role, text, initials, sort_order, active) VALUES ('Mireille B.', 'Coach & formatrice — Bafoussam', 'J''avais un petit budget, ils ont trouvé une formule adaptée sans sacrifier la qualité. Le digital accessible, c''est vrai.', 'MB', 4, 1);
INSERT INTO testimonials (name, role, text, initials, sort_order, active) VALUES ('Éric F.', 'Startup fintech — Douala', 'Le MVP de notre SaaS est sorti en 6 semaines. Code propre, bonne archi, on a levé nos premiers fonds avec cette démo.', 'EF', 5, 1);
INSERT INTO testimonials (name, role, text, initials, sort_order, active) VALUES ('Nadège E.', 'ONG locale — Limbé', 'Site multilingue, don en ligne, formation de notre équipe : tout était compris. Un vrai partenaire, pas juste un prestataire.', 'NE', 6, 1);
INSERT INTO testimonials (name, role, text, initials, sort_order, active) VALUES ('Boris A.', 'Agence immobilière — Bonamoussadi', 'Nos annonces sont en ligne en deux clics et les clients nous trouvent sur Google. Meilleur investissement de l''année.', 'BA', 7, 1);
INSERT INTO testimonials (name, role, text, initials, sort_order, active) VALUES ('Sandrine P.', 'Pâtisserie artisanale — Akwa', 'Ils ont créé une identité qui me ressemble et un site aussi gourmand que mes gâteaux. Les commandes arrivent via le site !', 'SP', 8, 1);

INSERT INTO faqs (question, answer, sort_order, active) VALUES ('Le prix affiché est-il vraiment tout compris ?', 'Oui. Design, développement, nom de domaine, hébergement la première année, certificat SSL et mise en ligne sont inclus. La seule dépense future est le renouvellement domaine + hébergement (à partir de la 2e année), annoncé dès le devis.', 0, 1);
INSERT INTO faqs (question, answer, sort_order, active) VALUES ('Puis-je payer en plusieurs fois ?', 'Oui. En général : un acompte au démarrage, un paiement à la validation du design, et le solde à la livraison. On s''adapte à votre trésorerie — parlons-en simplement.', 1, 1);
INSERT INTO faqs (question, answer, sort_order, active) VALUES ('Combien de temps pour avoir mon site en ligne ?', 'Une landing page est livrée en 2 semaines environ, un site vitrine en 3 semaines, un e-commerce en 4 à 6 semaines. Le délai exact est fixé dans le devis et on s''y tient.', 2, 1);
INSERT INTO faqs (question, answer, sort_order, active) VALUES ('Pourrai-je modifier mon site moi-même ?', 'Oui. On vous livre un espace d''administration simple et on vous forme (en visio ou à Douala). Textes, photos, articles, produits : vous êtes autonome. Et si besoin, notre support reste disponible.', 3, 1);
INSERT INTO faqs (question, answer, sort_order, active) VALUES ('Proposez-vous le paiement Mobile Money sur les boutiques ?', 'Absolument — c''est même indispensable au Cameroun. On intègre MTN Mobile Money, Orange Money et les cartes bancaires selon vos besoins.', 4, 1);
INSERT INTO faqs (question, answer, sort_order, active) VALUES ('Que se passe-t-il après la livraison ?', 'Chaque pack inclut une période de support (corrections, questions, petites retouches). Ensuite, vous pouvez continuer en toute autonomie ou souscrire une maintenance mensuelle légère.', 5, 1);

INSERT INTO posts (title, category, date, read_time, excerpt, image, featured, sort_order, active) VALUES ('Mobile Money sur votre site : pourquoi c''est indispensable au Cameroun', 'Conseils', '28 juin 2026', '5 min', 'MTN MoMo et Orange Money représentent l''écrasante majorité des paiements en ligne au Cameroun. Si votre boutique n''accepte que la carte bancaire, vous perdez des ventes chaque jour. Voici comment intégrer le paiement mobile, combien ça coûte et les pièges à éviter.', '/images/blog-1.jpg', 1, 0, 1);
INSERT INTO posts (title, category, date, read_time, excerpt, image, featured, sort_order, active) VALUES ('Combien coûte vraiment un site web professionnel en 2026 ?', 'Guide', '15 juin 2026', '7 min', 'Domaine, hébergement, design, maintenance : on décompose tout, sans langue de bois.', '/images/blog-2.jpg', 0, 1, 1);
INSERT INTO posts (title, category, date, read_time, excerpt, image, featured, sort_order, active) VALUES ('De la boutique de quartier à 100 commandes en ligne par mois', 'Success story', '2 juin 2026', '4 min', 'Comment un commerçant de Douala a digitalisé son activité avec un simple pack e-commerce.', '/images/blog-3.jpg', 0, 2, 1);
INSERT INTO posts (title, category, date, read_time, excerpt, image, featured, sort_order, active) VALUES ('5 signes que votre entreprise a besoin d''un site web (maintenant)', 'Conseils', '20 mai 2026', '6 min', 'Vos clients vous cherchent sur Google et trouvent... vos concurrents. On fait le point.', '/images/service-blog.jpg', 0, 3, 1);
INSERT INTO posts (title, category, date, read_time, excerpt, image, featured, sort_order, active) VALUES ('SaaS, application, site web : quelle solution pour votre idée ?', 'Guide', '8 mai 2026', '8 min', 'Les différences expliquées simplement, avec des exemples et des budgets réalistes.', '/images/service-saas.jpg', 0, 4, 1);
INSERT INTO posts (title, category, date, read_time, excerpt, image, featured, sort_order, active) VALUES ('Tok Tok Livraison : une app pensée pour les rues de Douala', 'Success story', '25 avril 2026', '5 min', 'Suivi en temps réel, paiement mobile, mode hors-ligne : les coulisses d''une app locale.', '/images/project-delivery.jpg', 0, 5, 1);
INSERT INTO posts (title, category, date, read_time, excerpt, image, featured, sort_order, active) VALUES ('Landing page : 7 éléments qui font (vraiment) convertir', 'Conseils', '10 avril 2026', '4 min', 'Titre, preuve sociale, appel à l''action... la checklist qu''on applique sur chaque projet.', '/images/service-landing.jpg', 0, 6, 1);

INSERT INTO projects (title, category, description, result, image, sort_order, active) VALUES ('Saveurs du Wouri — restaurant', 'Landing Page', 'Landing de réservation avec menu du jour et WhatsApp direct.', '+40 réservations / mois', '/images/project-landing.jpg', 0, 1);
INSERT INTO projects (title, category, description, result, image, sort_order, active) VALUES ('Kmer Style — mode & wax', 'E-commerce', 'Boutique en ligne avec paiement MTN MoMo et Orange Money.', 'Ventes x2 en 2 mois', '/images/project-ecommerce.jpg', 1, 1);
INSERT INTO projects (title, category, description, result, image, sort_order, active) VALUES ('Cabinet Nkotti — conseil juridique', 'Vitrine', 'Site vitrine sobre et crédible, avec blog d''actualités juridiques.', '1er sur Google local', '/images/service-blog.jpg', 2, 1);
INSERT INTO projects (title, category, description, result, image, sort_order, active) VALUES ('GestiStock — SaaS de gestion', 'SaaS & App', 'MVP SaaS de gestion de stock pour commerces, multi-boutiques.', 'MVP livré en 8 semaines', '/images/service-saas.jpg', 3, 1);
INSERT INTO projects (title, category, description, result, image, sort_order, active) VALUES ('Tok Tok Livraison — app mobile', 'SaaS & App', 'Application de livraison avec suivi en temps réel et paiement mobile.', '5 000+ livraisons suivies', '/images/project-delivery.jpg', 4, 1);
INSERT INTO projects (title, category, description, result, image, sort_order, active) VALUES ('Collège Les Bâtisseurs — plateforme', 'Sur-mesure', 'Portail notes & scolarité : parents, élèves et administration connectés.', '800 familles utilisatrices', '/images/project-school.jpg', 5, 1);
INSERT INTO projects (title, category, description, result, image, sort_order, active) VALUES ('Immo Littoral — programme neuf', 'Landing Page', 'Page de captation de prospects pour un programme immobilier.', '120 prospects qualifiés', '/images/service-landing.jpg', 6, 1);
INSERT INTO projects (title, category, description, result, image, sort_order, active) VALUES ('TransCam Logistics — outil interne', 'Sur-mesure', 'Suivi de flotte et des expéditions, tableaux de bord dirigeants.', '-30% de temps administratif', '/images/project-custom.jpg', 7, 1);
INSERT INTO projects (title, category, description, result, image, sort_order, active) VALUES ('Artisanat Bafoussam — export', 'E-commerce', 'Boutique bilingue FR/EN pour vendre l''artisanat camerounais à l''international.', 'Clients dans 12 pays', '/images/blog-3.jpg', 8, 1);

INSERT INTO process_steps (num, title, description, sort_order, active) VALUES ('01', 'Échange', 'On écoute votre projet, vos objectifs et votre budget. Premier rendez-vous gratuit, en ligne ou à Douala.', 0, 1);
INSERT INTO process_steps (num, title, description, sort_order, active) VALUES ('02', 'Devis clair', 'Sous 48h, vous recevez une proposition détaillée : prix fixe, délais, livrables. Zéro frais caché.', 1, 1);
INSERT INTO process_steps (num, title, description, sort_order, active) VALUES ('03', 'Design & Dev', 'On conçoit, vous validez à chaque étape. Vous suivez l''avancement en temps réel, sans jargon technique.', 2, 1);
INSERT INTO process_steps (num, title, description, sort_order, active) VALUES ('04', 'Livraison & suivi', 'Mise en ligne, formation à la prise en main et support continu. On reste à vos côtés après la livraison.', 3, 1);
