export const FIELD_TYPES = { text: "text", textarea: "textarea", number: "number", bool: "bool", list: "list" };

export const RESOURCES = [
  {
    key: "services",
    label: "Services",
    icon: "Puzzle",
    titleField: "title",
    fields: [
      { name: "title", label: "Titre", type: "text", required: true },
      { name: "slug", label: "Slug (ancre URL)", type: "text", required: true },
      { name: "tag", label: "Tag (badge)", type: "text" },
      { name: "short_desc", label: "Description courte (carte accueil)", type: "text" },
      { name: "headline", label: "Titre détaillé (page services)", type: "text" },
      { name: "accent", label: "Mot accentué du titre", type: "text" },
      { name: "description", label: "Description complète", type: "textarea" },
      { name: "features", label: "Inclusions (une par ligne)", type: "list" },
      { name: "ideal", label: "Idéal pour", type: "text" },
      { name: "price", label: "Prix (ex : 200 000 FCFA ou Sur devis)", type: "text" },
      { name: "delay", label: "Délai (ex : ≈ 2 semaines)", type: "text" },
      { name: "image", label: "Image", type: "image" },
      { name: "sort_order", label: "Ordre d'affichage", type: "number" },
      { name: "active", label: "Visible sur le site", type: "bool", default: 1 },
    ],
  },
  {
    key: "offers",
    label: "Offres (packs)",
    icon: "Briefcase",
    titleField: "tag",
    fields: [
      { name: "tag", label: "Nom du pack", type: "text", required: true },
      { name: "title", label: "Titre / accroche", type: "text", required: true },
      { name: "description", label: "Explication du pack", type: "textarea" },
      { name: "price", label: "Prix (ex : 200 000 ou Sur devis)", type: "text" },
      { name: "is_quote", label: "Sur devis (pas de FCFA affiché)", type: "bool" },
      { name: "popular", label: "Badge « Le plus demandé »", type: "bool" },
      { name: "features", label: "Inclusions (une par ligne)", type: "list" },
      { name: "image", label: "Image", type: "image" },
      { name: "sort_order", label: "Ordre d'affichage", type: "number" },
      { name: "active", label: "Visible sur le site", type: "bool", default: 1 },
    ],
  },
  {
    key: "projects",
    label: "Réalisations",
    icon: "Building2",
    titleField: "title",
    fields: [
      { name: "title", label: "Titre du projet", type: "text", required: true },
      { name: "category", label: "Catégorie (filtre)", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "result", label: "Résultat obtenu (ex : Ventes x2)", type: "text" },
      { name: "image", label: "Image", type: "image" },
      { name: "sort_order", label: "Ordre d'affichage", type: "number" },
      { name: "active", label: "Visible sur le site", type: "bool", default: 1 },
    ],
  },
  {
    key: "testimonials",
    label: "Avis clients",
    icon: "Star",
    titleField: "name",
    fields: [
      { name: "name", label: "Nom", type: "text", required: true },
      { name: "role", label: "Rôle / activité", type: "text" },
      { name: "text", label: "Témoignage", type: "textarea", required: true },
      { name: "initials", label: "Initiales (avatar)", type: "text" },
      { name: "sort_order", label: "Ordre d'affichage", type: "number" },
      { name: "active", label: "Visible sur le site", type: "bool", default: 1 },
    ],
  },
  {
    key: "stats",
    label: "Chiffres clés",
    icon: "BarChart3",
    titleField: "label",
    fields: [
      { name: "label", label: "Libellé (ex : Projets livrés)", type: "text", required: true },
      { name: "value", label: "Valeur (nombre)", type: "number", required: true },
      { name: "suffix", label: "Suffixe (ex : +, %, jours)", type: "text" },
      { name: "note", label: "Note (sous le libellé)", type: "text" },
      { name: "sort_order", label: "Ordre d'affichage", type: "number" },
      { name: "active", label: "Visible sur le site", type: "bool", default: 1 },
    ],
  },
  {
    key: "faqs",
    label: "FAQ",
    icon: "HelpCircle",
    titleField: "question",
    fields: [
      { name: "question", label: "Question", type: "text", required: true },
      { name: "answer", label: "Réponse", type: "textarea", required: true },
      { name: "sort_order", label: "Ordre d'affichage", type: "number" },
      { name: "active", label: "Visible sur le site", type: "bool", default: 1 },
    ],
  },
  {
    key: "posts",
    label: "Blog",
    icon: "Newspaper",
    titleField: "title",
    fields: [
      { name: "title", label: "Titre de l'article", type: "text", required: true },
      { name: "category", label: "Catégorie (ex : Conseils, Guide)", type: "text" },
      { name: "date", label: "Date affichée (ex : 28 juin 2026)", type: "text" },
      { name: "read_time", label: "Temps de lecture (ex : 5 min)", type: "text" },
      { name: "author", label: "Auteur affiché", type: "text" },
      { name: "image", label: "Image de couverture", type: "image" },
      { name: "excerpt", label: "Extrait (résumé)", type: "textarea" },
      { name: "eyebrow", label: "Sur-titre", type: "text" },
      { name: "lead", label: "Chapô / accroche d'introduction", type: "textarea" },
      { name: "secondary_image", label: "Image secondaire", type: "image" },
      { name: "sections", label: "Contenu de l'article", type: "sections" },
      { name: "featured", label: "Article à la une", type: "bool" },
      { name: "sort_order", label: "Ordre d'affichage", type: "number" },
      { name: "active", label: "Visible sur le site", type: "bool", default: 1 },
    ],
  },
  {
    key: "process-steps",
    label: "Méthode (étapes)",
    icon: "Layers",
    titleField: "title",
    fields: [
      { name: "num", label: "Numéro (ex : 01)", type: "text" },
      { name: "title", label: "Titre de l'étape", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "sort_order", label: "Ordre d'affichage", type: "number" },
      { name: "active", label: "Visible sur le site", type: "bool", default: 1 },
    ],
  },
];

export const SETTINGS_FIELDS = [
  { name: "site_name", label: "Nom du site" },
  { name: "phone_display", label: "Téléphone affiché" },
  { name: "phone_link", label: "Téléphone (format lien, ex : +237600000000)" },
  { name: "email", label: "Email de contact" },
  { name: "address", label: "Adresse / localisation" },
  { name: "hours", label: "Horaires" },
  { name: "location_note", label: "Note localisation" },
  { name: "hours_note", label: "Note horaires" },
  { name: "facebook", label: "Lien Facebook" },
  { name: "linkedin", label: "Lien LinkedIn" },
  { name: "instagram", label: "Lien Instagram" },
  { name: "tiktok", label: "Lien TikTok" },
  { name: "marquee_items", label: "Bandeau défilant (un mot par ligne)", type: "list" },
  { name: "hero_pills", label: "Arguments du hero (un par ligne)", type: "list" },
];

export const REQUEST_STATUSES = [
  { value: "new", label: "Nouvelle", color: "danger" },
  { value: "in_progress", label: "En cours", color: "warning" },
  { value: "done", label: "Traitée", color: "success" },
];

export const PAYMENT_STATUSES = {
  COMPLETED: { label: "Payé", color: "success" },
  PENDING: { label: "En attente", color: "warning" },
  FAILED: { label: "Échoué", color: "danger" },
  CANCELLED: { label: "Annulé", color: "default" },
};

export const TABS = [
  { key: "dashboard", label: "Tableau de bord", icon: "Home", section: "PRINCIPAL" },
  { key: "requests", label: "Demandes", icon: "FileText", section: "PRINCIPAL" },
  { key: "payments", label: "Paiements", icon: "CreditCard", section: "PRINCIPAL" },
  { key: "services", label: "Services", icon: "Puzzle", section: "CONTENU" },
  { key: "offers", label: "Offres (packs)", icon: "Briefcase", section: "CONTENU" },
  { key: "projects", label: "Réalisations", icon: "Building2", section: "CONTENU" },
  { key: "testimonials", label: "Avis clients", icon: "Star", section: "CONTENU" },
  { key: "stats", label: "Chiffres clés", icon: "BarChart3", section: "CONTENU" },
  { key: "faqs", label: "FAQ", icon: "HelpCircle", section: "CONTENU" },
  { key: "posts", label: "Blog", icon: "Newspaper", section: "CONTENU" },
  { key: "process-steps", label: "Méthode", icon: "Layers", section: "CONTENU" },
  { key: "surveys", label: "Enquêtes", icon: "ClipboardList", section: "OUTILS" },
  { key: "appointments", label: "Agenda", icon: "Calendar", section: "OUTILS" },
  { key: "portal", label: "Portail Client", icon: "Users", section: "OUTILS" },
  { key: "subscribers", label: "Newsletter", icon: "Mail", section: "OUTILS" },
  { key: "settings", label: "Réglages", icon: "Settings", section: "SYSTÈME" },
];
